name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run action
      id: run_action
      uses: ./

    - uses: luisghz/simple-ms-teams-webhook-notifier@v1
      name: test my webhook notifier
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        summary: 'SUMMARY TEST'
        title: 'TITLE TEST'
        text: 'TITLE TEXT'